FROM node:12

LABEL repository="https://github.com/oddysee/resume"
LABEL homepage="https://github.com/oddysee/resume"
LABEL maintainer="Suman Jayapathi <sj@oddysee.com.au>"

WORKDIR /app

ENV PUPPETEER_SKIP_DOWNLOAD=true
RUN npm install -g resume-cli@3.0.8

CMD [ "./resume serve" ]
EXPOSE 4000