FROM node:12

LABEL repository="https://github.com/oddysee/resume"
LABEL homepage="https://github.com/oddysee/resume"
LABEL maintainer="Suman Jayapathi <sj@oddysee.com.au>"

WORKDIR /app

ENV PUPPETEER_SKIP_DOWNLOAD=true
RUN npm install -g --unsafe-perm resume-cli@3.0.8
RUN npm install jsonresume-theme-even@0.6.0

CMD [ "resume", "serve", "--resume", "/src/resume.json" ]
EXPOSE 4000