ARG CLI_VERSION=3.0.8
ARG NODE_VERSION=12

FROM node:$NODE_VERSION

LABEL repository="https://github.com/oddysee/resume"
LABEL homepage="https://github.com/oddysee/resume"
LABEL maintainer="Suman Jayapathi <sj@oddysee.com.au>"

WORKDIR /app

ENV PUPPETEER_SKIP_DOWNLOAD=true
RUN npm install -g resume-cli

CMD [ "./resume serve" ]
EXPOSE 4000