# action.yml
name: 'JSONResume Export'
description: 'Simple GitHub Action to export your JSONResume'
branding:
  icon: 'printer'
  color: 'blue'
inputs:
  theme:
    description: |
      JSONResume theme name.
      Assumes the theme package would be found 
      as `jsonresume-theme-{theme}` in NPM.
      You can search for themes at https://npmsearch.com/?q=jsonresume-theme
    required: true
    default: 'flat'
  theme_version:
    description: |
      JSONResume theme version
      Updates to themes have a habit of breaking the CLI's output
    required: true
    default: '0.6.0'
  resume_filepath:
    description: |
      File path of the resume in JSONResume format
    required: false
    default: 'resume.json'
  output_filepath:
    description: |
      Output file path for exported HTML file.
    required: false
    default: 'index.html'
runs:
  using: 'docker'
  image: '../../../Dockerfile'
  args:
    - ${{ inputs.theme }}
    - ${{ inputs.theme_version }}
    - ${{ inputs.resume_filepath }}
    - ${{ inputs.output_filepath }}
